### ISSUE TITLE
Impossible to access the netlify admin page (Error loading the CMS configuration)

### ISSUE THREAD

**Issue by tosky** [beta-europe/italy.beta-europe.org#6]
It seems we can't access the Content manager site from the /admin subpage anymore. I can't track down the exact date when it started, but it happened in the last month. The following error is shown:

> Error loading the CMS configuration
> Config Errors:

> 'collections[0].meta' should be object

> Check your config.yml file.

I think the same error is visible on all /admin/ pages for all beta-europe websites. Maybe an core update requires some new configuration?

**Comment by tosky** [comment]
@CKroes97 definitely need your help here!

**Comment by CKroes97** [comment]
On it!

**Comment by CKroes97** [comment]
Should work now, feel free to contact me if you need any more help :) And thanks for the heads-up! I normally don't use the CMS so wouldn't have noticed.

**Comment by tosky** [comment]
Thanks! I confirm it works. As we are here: do we need this https://github.com/beta-europe/italy.beta-europe.org/pull/5 ?

**Comment by CKroes97** [comment]
Dependabot pulls I'd always allow. Our set-up is extremely low-risk but they've never broken anything in my experience and more security = better
